spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}  # 운영에서도 테이블 자동 생성
    show-sql: ${SPRING_JPA_SHOW_SQL:false}  # 운영에서는 SQL 로그 비활성화
  
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}  # docker-compose의 redis 서비스명
      port: ${SPRING_DATA_REDIS_PORT:6379}
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}  # 30분
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}  # 7일

#ncp:
#  clova:
#    base-url: https://clovastudio.apigw.ntruss.com/testapp/v1/chat-completions
#    api-key: ${NCP_CLOVA_API_KEY}
#    model: HCX-005

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo